# Generated by Django 4.2.7 on 2023-11-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_activs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='activs',
            new_name='active',
        ),
    ]
